### ISSUE TITLE
TypeScript definition should export a default function

### ISSUE THREAD

**Issue by steveluscher** [ndavd/hashprintjs#1]
## Repro:

1. Add `import hashprint from 'hashprintjs';` in a brand new Next.JS project.

Observe TypeScript error.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/13243/161109243-81503e43-3d90-4264-9d61-a5cd054e6417.png">

If the index.d.ts file read like this:

```
export default function GenerateHashprint(opts: Opts): Promise<string>;
```

…everything would work.

**Comment by ndavd** [comment]
Thanks! Should be working now :]
